import React, { useMemo, useState } from 'react';
import { Alert, Modal, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import DateTimePicker from '@react-native-community/datetimepicker';
import { Ionicons } from '@expo/vector-icons';
import Animated, { FadeIn, FadeInDown, useAnimatedStyle, useSharedValue, withSpring } from 'react-native-reanimated';
import AnimalAvatar, { AVATARS } from './avatars/AnimalAvatar';
import colors from '../theme/colors';

export default function EditProfileSheet({ visible, profile, onClose, onSave }) {
  const [draft, setDraft] = useState(profile);
  const [pickerOpen, setPickerOpen] = useState(false);
  const [pendingDate, setPendingDate] = useState(new Date(profile.dateOfBirth || '2000-01-01'));
  const scale = useSharedValue(1);
  const changed = useMemo(() => JSON.stringify(draft) !== JSON.stringify(profile), [draft, profile]);
  const avatarStyle = useAnimatedStyle(() => ({ transform: [{ scale: scale.value }] }));
  const chooseAvatar = (avatarId) => { setDraft((current) => ({ ...current, avatarId })); scale.value = .94; scale.value = withSpring(1, { damping: 11, stiffness: 180 }); };
  const save = () => {
    if (!draft.name.trim()) return Alert.alert('Name required', 'Enter a name to continue.');
    if (!/^\S+@\S+\.\S+$/.test(draft.email.trim())) return setDraft((current) => ({ ...current, emailError: true }));
    onSave({ ...draft, name: draft.name.trim(), email: draft.email.trim() });
  };
  const date = new Date(draft.dateOfBirth || '2000-01-01');
  return <Modal visible={visible} animationType="slide" presentationStyle="pageSheet" onRequestClose={onClose} onShow={() => { setDraft(profile); setPendingDate(new Date(profile.dateOfBirth || '2000-01-01')); }}>
    <View style={styles.sheet}><View style={styles.header}><TouchableOpacity onPress={onClose} style={styles.headerButton}><Ionicons name="chevron-back" size={25} color={colors.text}/></TouchableOpacity><Text style={styles.title}>Edit Profile</Text><TouchableOpacity disabled={!changed} onPress={save} style={styles.save}><Text style={[styles.saveText, !changed && styles.disabled]}>Save</Text></TouchableOpacity></View>
      <ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
        <Animated.View entering={FadeIn.duration(250)} style={[styles.preview, avatarStyle]}><AnimalAvatar avatarId={draft.avatarId} size={118}/></Animated.View>
        <Text style={styles.change}>Change Avatar</Text>
        <View style={styles.grid}>{AVATARS.map((avatar) => <TouchableOpacity key={avatar.id} onPress={() => chooseAvatar(avatar.id)} style={[styles.avatarChoice, draft.avatarId === avatar.id && styles.avatarSelected]}><AnimalAvatar avatarId={avatar.id} size={55}/>{draft.avatarId === avatar.id && <View style={styles.check}><Ionicons name="checkmark" color="#fff" size={12}/></View>}</TouchableOpacity>)}</View>
        <Text style={styles.label}>Name</Text><TextInput value={draft.name} onChangeText={(name) => setDraft((current) => ({ ...current, name }))} placeholder="Enter your name" placeholderTextColor={colors.textMuted} style={styles.input}/>
        <Text style={styles.label}>Date of Birth</Text><TouchableOpacity onPress={() => { setPendingDate(date); setPickerOpen(true); }} style={styles.dateField}><Text style={styles.dateText}>{date.toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}</Text><Ionicons name="calendar-outline" color={colors.primarySoft} size={20}/></TouchableOpacity>
        <Text style={styles.label}>Email</Text><TextInput value={draft.email} onChangeText={(email) => setDraft((current) => ({ ...current, email, emailError: false }))} keyboardType="email-address" autoCapitalize="none" placeholder="Enter your email" placeholderTextColor={colors.textMuted} style={[styles.input, draft.emailError && styles.errorInput]}/>{draft.emailError && <Text style={styles.error}>Enter a valid email address.</Text>}
        <Animated.View entering={FadeInDown.duration(280)}><TouchableOpacity disabled={!changed} onPress={save} style={[styles.bottomSave, !changed && styles.bottomDisabled]}><Text style={styles.bottomSaveText}>Save changes</Text></TouchableOpacity></Animated.View>
      </ScrollView>
      {pickerOpen && <View style={styles.pickerPanel}><View style={styles.pickerHeader}><TouchableOpacity onPress={() => setPickerOpen(false)}><Text style={styles.pickerAction}>Cancel</Text></TouchableOpacity><Text style={styles.pickerTitle}>Date of Birth</Text><TouchableOpacity onPress={() => { setDraft((current) => ({ ...current, dateOfBirth: pendingDate.toISOString() })); setPickerOpen(false); }}><Text style={styles.pickerAction}>Done</Text></TouchableOpacity></View><DateTimePicker value={pendingDate} mode="date" display="spinner" maximumDate={new Date()} onChange={(_, selectedDate) => selectedDate && setPendingDate(selectedDate)} /></View>}
    </View>
  </Modal>;
}
const styles = StyleSheet.create({ sheet:{ flex:1, backgroundColor:'#141c2c', paddingTop:18 }, header:{ height:54, flexDirection:'row', alignItems:'center', justifyContent:'space-between', paddingHorizontal:16, borderBottomWidth:1, borderBottomColor:'rgba(255,255,255,.07)' }, headerButton:{ width:46 }, title:{ color:'#fffaf0', fontSize:17, fontWeight:'800' }, save:{ width:46, alignItems:'flex-end' }, saveText:{ color:'#eabf79', fontSize:16, fontWeight:'800' }, disabled:{ opacity:.35 }, content:{ padding:24, paddingBottom:48 }, preview:{ alignSelf:'center', width:126, height:126, borderRadius:63, backgroundColor:'#26344b', justifyContent:'center', alignItems:'center', marginTop:6, shadowColor:'#000', shadowOpacity:.25, shadowRadius:16, elevation:6 }, change:{ textAlign:'center', color:'#eabf79', fontSize:14, fontWeight:'700', marginTop:12, marginBottom:20 }, grid:{ flexDirection:'row', flexWrap:'wrap', justifyContent:'space-between', gap:10, marginBottom:28 }, avatarChoice:{ width:'17%', aspectRatio:1, borderRadius:30, justifyContent:'center', alignItems:'center', backgroundColor:'#1d2940', borderWidth:2, borderColor:'transparent' }, avatarSelected:{ borderColor:'#eabf79', backgroundColor:'#2a3a55' }, check:{ position:'absolute', right:-2, bottom:-2, width:18, height:18, borderRadius:9, backgroundColor:'#d98b5f', justifyContent:'center', alignItems:'center' }, label:{ color:'#dfe6dc', fontWeight:'700', fontSize:14, marginBottom:9 }, input:{ color:'#fffaf0', backgroundColor:'#1d2940', borderColor:'#34445d', borderWidth:1, borderRadius:18, paddingHorizontal:16, paddingVertical:15, fontSize:16, marginBottom:20 }, dateField:{ flexDirection:'row', justifyContent:'space-between', alignItems:'center', backgroundColor:'#1d2940', borderColor:'#34445d', borderWidth:1, borderRadius:18, paddingHorizontal:16, paddingVertical:16, marginBottom:20 }, dateText:{ color:'#fffaf0', fontSize:16 }, errorInput:{ borderColor:colors.danger }, error:{ color:colors.dangerSoft, fontSize:12, marginTop:-15, marginBottom:15 }, bottomSave:{ backgroundColor:'#d98b5f', borderRadius:20, paddingVertical:17, alignItems:'center', marginTop:8 }, bottomDisabled:{ opacity:.42 }, bottomSaveText:{ color:'#fffaf0', fontWeight:'800', fontSize:16 }, pickerPanel:{ position:'absolute', left:0, right:0, bottom:0, backgroundColor:'#202d45', borderTopLeftRadius:26, borderTopRightRadius:26, paddingBottom:20, shadowColor:'#000', shadowOpacity:.32, shadowRadius:18, elevation:12 }, pickerHeader:{ flexDirection:'row', alignItems:'center', justifyContent:'space-between', padding:18, borderBottomWidth:1, borderBottomColor:'rgba(255,255,255,.08)' }, pickerAction:{ color:'#eabf79', fontSize:16, fontWeight:'800' }, pickerTitle:{ color:'#fffaf0', fontSize:16, fontWeight:'800' } });
