import React, { useMemo, useState } from 'react';
import { Modal, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import colors from '../theme/colors';

export default function FinanceAssistant({ transactions }) {
  const [open, setOpen] = useState(false); const [question, setQuestion] = useState(''); const [answer, setAnswer] = useState('Ask me about your spending.');
  const totals = useMemo(() => ({ spent: transactions.filter(item=>item.type==='Expense').reduce((sum,item)=>sum+item.amount,0), biggest:[...transactions.filter(item=>item.type==='Expense')].sort((a,b)=>b.amount-a.amount)[0] }), [transactions]);
  const ask = () => { const text=question.toLowerCase(); if(text.includes('biggest')) setAnswer(totals.biggest ? `Your largest expense was ${totals.biggest.category || 'an expense'} at $${totals.biggest.amount.toFixed(2)}.` : 'You have not added any expenses yet.'); else if(text.includes('spent') || text.includes('spend')) setAnswer(`You have recorded $${totals.spent.toFixed(2)} in expenses.`); else if(text.includes('budget')) setAnswer(`A simple starting budget is 50% needs, 30% wants, and 20% savings. Based on your current activity, review your biggest category first.`); else setAnswer('I can help with spending, biggest expenses, food spending, and budget guidance.'); setQuestion(''); };
  return <><TouchableOpacity accessibilityLabel="Open finance assistant" onPress={()=>setOpen(true)} style={styles.fab}><Ionicons name="sparkles" size={21} color={colors.text}/></TouchableOpacity><Modal visible={open} transparent animationType="slide" onRequestClose={()=>setOpen(false)}><View style={styles.backdrop}><View style={styles.sheet}><View style={styles.header}><View><Text style={styles.kicker}>Velora assistant</Text><Text style={styles.title}>How can I help?</Text></View><TouchableOpacity onPress={()=>setOpen(false)} style={styles.close}><Ionicons name="close" size={20} color={colors.text}/></TouchableOpacity></View><View style={styles.answer}><Ionicons name="sparkles" size={17} color={colors.primarySoft}/><Text style={styles.answerText}>{answer}</Text></View><Text style={styles.suggestion}>Try “How much did I spend?” or “What should my budget be?”</Text><View style={styles.inputRow}><TextInput value={question} onChangeText={setQuestion} onSubmitEditing={ask} placeholder="Ask about your money" placeholderTextColor={colors.textMuted} style={styles.input}/><TouchableOpacity onPress={ask} style={styles.send}><Ionicons name="arrow-up" size={20} color={colors.text}/></TouchableOpacity></View></View></View></Modal></>;
}
const styles=StyleSheet.create({fab:{position:'absolute',right:20,bottom:88,width:52,height:52,borderRadius:26,backgroundColor:colors.primary,alignItems:'center',justifyContent:'center',zIndex:20,shadowColor:'#000',shadowOpacity:.35,shadowRadius:10,shadowOffset:{width:0,height:5},elevation:8},backdrop:{flex:1,backgroundColor:'rgba(0,0,0,.6)',justifyContent:'flex-end'},sheet:{backgroundColor:colors.surface,borderTopLeftRadius:30,borderTopRightRadius:30,padding:24,paddingBottom:36,borderWidth:1,borderColor:colors.border},header:{flexDirection:'row',justifyContent:'space-between',marginBottom:20},kicker:{color:colors.primarySoft,fontSize:12,fontWeight:'700',letterSpacing:1,textTransform:'uppercase',marginBottom:5},title:{color:colors.text,fontSize:24,fontWeight:'800'},close:{backgroundColor:colors.surfaceAlt,width:36,height:36,borderRadius:18,alignItems:'center',justifyContent:'center'},answer:{flexDirection:'row',gap:10,backgroundColor:colors.surfaceMuted,borderRadius:18,padding:16,marginBottom:14},answerText:{color:colors.textSoft,flex:1,lineHeight:21},suggestion:{color:colors.textMuted,fontSize:12,lineHeight:18,marginBottom:16},inputRow:{flexDirection:'row',gap:10},input:{flex:1,backgroundColor:colors.surfaceMuted,borderColor:colors.border,borderWidth:1,borderRadius:18,paddingHorizontal:15,color:colors.text},send:{width:50,height:50,borderRadius:18,backgroundColor:colors.primary,alignItems:'center',justifyContent:'center'}});
